{% set name = "pybuilder-bandit" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybuilder-bandit-{{ version }}.tar.gz
  sha256: d37269c95b1aaf89d5c91de1226e1e770cf1635f721e3a9701fe59495cfc93a2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - bandit
    - pybuilder

test:
  imports:
    - pybuilder_bandit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/soda480/pybuilder-bandit
  summary: Pybuilder plugin for bandit security linter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
