{% set name = "pybuilder-bandit" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybuilder-bandit-{{ version }}.tar.gz
  sha256: e410832729acbac5468e5113f4265d311267374be2d598d76b875fad980bf57f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - bandit
    - pybuilder

test:
  imports:
    - pybuilder_bandit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/soda480/pybuilder-bandit
  summary: Pybuilder plugin for bandit security linter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
